# Generated by Django 6.0.3 on 2026-03-25 05:23

import core.models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='学校名 / 法人名')),
                ('last_name', models.CharField(max_length=50, verbose_name='氏（姓）')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('last_name_kana', models.CharField(max_length=50, verbose_name='セイ')),
                ('first_name_kana', models.CharField(max_length=50, verbose_name='メイ')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年齢')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=10, verbose_name='性別')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('contact_method', models.CharField(choices=[('email', 'メール'), ('phone', '電話')], default='email', max_length=10, verbose_name='ご連絡方法')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('phone_type', models.CharField(choices=[('home', '自宅'), ('work', '勤務先'), ('mobile', '携帯')], default='home', max_length=10, verbose_name='電話種別')),
                ('prefecture', models.CharField(choices=[('hokkaido', '北海道'), ('aomori', '青森県'), ('iwate', '岩手県'), ('miyagi', '宮城県'), ('akita', '秋田県'), ('yamagata', '山形県'), ('fukushima', '福島県'), ('ibaraki', '茨城県'), ('tochigi', '栃木県'), ('gunma', '群馬県'), ('saitama', '埼玉県'), ('chiba', '千葉県'), ('tokyo', '東京都'), ('kanagawa', '神奈川県'), ('niigata', '新潟県'), ('toyama', '富山県'), ('ishikawa', '石川県'), ('fukui', '福井県'), ('yamanashi', '山梨県'), ('nagano', '長野県'), ('gifu', '岐阜県'), ('shizuoka', '静岡県'), ('aichi', '愛知県'), ('mie', '三重県'), ('shiga', '滋賀県'), ('kyoto', '京都府'), ('osaka', '大阪府'), ('hyogo', '兵庫県'), ('nara', '奈良県'), ('wakayama', '和歌山県'), ('tottori', '鳥取県'), ('shimane', '島根県'), ('okayama', '岡山県'), ('hiroshima', '広島県'), ('yamaguchi', '山口県'), ('tokushima', '徳島県'), ('kagawa', '香川県'), ('ehime', '愛媛県'), ('kochi', '高知県'), ('fukuoka', '福岡県'), ('saga', '佐賀県'), ('nagasaki', '長崎県'), ('kumamoto', '熊本県'), ('oita', '大分県'), ('miyazaki', '宮崎県'), ('kagoshima', '鹿児島県'), ('okinawa', '沖縄県')], max_length=50, verbose_name='都道府県')),
                ('contact_time', models.CharField(choices=[('nothing', '特に希望なし'), ('morning', '午前'), ('afternoon', '午後'), ('evening', '夕方以降')], default='nothing', max_length=50, verbose_name='時間帯')),
                ('content_type', models.CharField(choices=[('service', 'サービスに関するお問い合わせ'), ('recruit', '採用に関するお問い合わせ'), ('other', 'その他')], default='service', max_length=50, verbose_name='内容')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('is_processed', models.BooleanField(default=False, help_text='対応済みかどうかを指定します。', verbose_name='対応済み')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ニュースのタイトルを入力します。', max_length=200, verbose_name='タイトル')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='URLに使用されるスラッグを入力します。', max_length=100, unique=True, verbose_name='スラッグ')),
                ('order', models.PositiveIntegerField(db_index=True, help_text='ニュースの表示順序を指定します。', verbose_name='オーダー')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='日付を入力します。', verbose_name='日付')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='ニュースの内容を入力します。', verbose_name='内容')),
                ('is_published', models.BooleanField(default=True, help_text='公開するかどうかを指定します。', verbose_name='公開する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'ニュース',
                'verbose_name_plural': 'ニュース一覧',
                'ordering': ['-order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URLに使用されるスラッグを入力します。', max_length=200, unique=True, verbose_name='スラッグ')),
                ('page_type', models.CharField(choices=[('basic_content', 'Basic Content'), ('company_profile', 'Company Profile'), ('greeting', 'Greeting / Message'), ('history', 'History Timeline'), ('global_network', 'Global Network')], default='basic_content', help_text='ページのタイプを選択します。', verbose_name='ページタイプ')),
                ('order', models.PositiveIntegerField(db_index=True, help_text='ページの表示順序を指定します。', verbose_name='オーダー')),
                ('image', models.ImageField(blank=True, help_text='ページのイメージをアップロードします。', null=True, upload_to='about_img/', verbose_name='イメージ')),
                ('is_published', models.BooleanField(default=True, help_text='ページを公開するかどうかを設定します。', verbose_name='公開済み')),
            ],
            options={
                'verbose_name': '企業情報',
                'verbose_name_plural': '企業情報一覧',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_postal_code', models.CharField(help_text='郵便番号を入力します。', max_length=8, verbose_name='郵便番号')),
                ('company_phone', models.CharField(help_text='電話番号を入力します。', max_length=50, verbose_name='TEL')),
                ('company_email', models.EmailField(help_text='メールアドレスを入力します。', max_length=50, verbose_name='メールアドレス')),
                ('logo_image', models.ImageField(blank=True, help_text='ロゴ画像をアップロードします。', null=True, upload_to='logo/', verbose_name='ロゴイメージ')),
                ('map_embed', models.TextField(blank=True, help_text='Google Maps埋め込みコードを入力します。', null=True, verbose_name='Google Maps埋め込みコード')),
            ],
            options={
                'verbose_name': 'サイト構成',
                'verbose_name_plural': 'サイト構成一覧',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], default=2026, verbose_name='年')),
                ('month', models.IntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], default=3, verbose_name='月')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='core.page')),
            ],
            options={
                'verbose_name': '沿革',
                'verbose_name_plural': '沿革一覧',
                'ordering': ['year', 'month'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo_image', models.ImageField(blank=True, help_text='代表取締役のイメージをアップロードします。', upload_to='about_img/greeting_ceo_img/', verbose_name='CEOイメージ')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greetings', to='core.page')),
            ],
            options={
                'verbose_name': '代表挨拶',
                'verbose_name_plural': '代表挨拶一覧',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GlobalNetworkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, help_text='郵便番号を入力します。', max_length=8, null=True, verbose_name='郵便番号')),
                ('phone', models.CharField(blank=True, help_text='電話番号を入力します。', max_length=50, null=True, verbose_name='TEL')),
                ('map_url', models.URLField(blank=True, help_text='Google Maps URL を入力します。', null=True, verbose_name='Google Maps URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='拠点の表示順序を指定します。', verbose_name='オーダー')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_networks', to='core.page')),
            ],
            options={
                'verbose_name': '拠点',
                'verbose_name_plural': '拠点一覧',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='core.page')),
            ],
            options={
                'verbose_name': '会社概要',
                'verbose_name_plural': '会社概要一覧',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BasicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_contents', to='core.page')),
            ],
            options={
                'verbose_name': '基本コンテンツ',
                'verbose_name_plural': '基本コンテンツ一覧',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_prefix', models.CharField(blank=True, help_text='URL prefix を入力します。 e.g., /about/, /business/', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='メニュー項目を表示するかどうかを選択します。', verbose_name='表示する')),
                ('image', models.ImageField(blank=True, help_text='メニュー項目のイメージをアップロードします。', null=True, upload_to='menu_img/', verbose_name='イメージ')),
                ('key', models.CharField(help_text='メニュー項目のキーを入力します。', max_length=50, unique=True, verbose_name='キー')),
                ('order', models.PositiveIntegerField(db_index=True, help_text='メニュー項目の並び順を入力します。', verbose_name='並び順')),
                ('site_config', models.ForeignKey(default=core.models.SiteConfiguration.get_solo, help_text='メニュー項目を入力します。', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.siteconfiguration')),
            ],
            options={
                'verbose_name': 'メニュー項目',
                'verbose_name_plural': 'メニュー項目一覧',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BasicContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('basic_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='ページの基本コンテンツを入力します。', null=True, verbose_name='基本コンテンツ')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.basiccontent')),
            ],
            options={
                'verbose_name': '基本コンテンツ Translation',
                'db_table': 'core_basiccontent_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyProfileTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='タイトルを入力します。', max_length=20, verbose_name='タイトル')),
                ('content', models.CharField(help_text='コンテンツを入力します。', verbose_name='コンテンツ')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.companyprofile')),
            ],
            options={
                'verbose_name': '会社概要 Translation',
                'db_table': 'core_companyprofile_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GlobalNetworkLocationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='拠点名を入力します。', max_length=200, verbose_name='拠点名')),
                ('address', models.CharField(help_text='住所を入力します。', max_length=200, verbose_name='住所')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.globalnetworklocation')),
            ],
            options={
                'verbose_name': '拠点 Translation',
                'db_table': 'core_globalnetworklocation_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GreetingTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('ceo_name', models.CharField(default='小森 雅之', help_text='代表取締役氏名を入力します。', max_length=100, verbose_name='代表取締役氏名')),
                ('message', django_ckeditor_5.fields.CKEditor5Field(help_text='メッセージを入力します。', verbose_name='メッセージ')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.greeting')),
            ],
            options={
                'verbose_name': '代表挨拶 Translation',
                'db_table': 'core_greeting_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoryEventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('event', models.TextField(help_text='イベントを入力します。', verbose_name='イベント')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.historyevent')),
            ],
            options={
                'verbose_name': '沿革 Translation',
                'db_table': 'core_historyevent_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MenuItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='メニュー項目を入力します。', max_length=100, verbose_name='メニュー項目')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.menuitem')),
            ],
            options={
                'verbose_name': 'メニュー項目 Translation',
                'db_table': 'core_menuitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='ページのタイトルを入力します。', max_length=200, verbose_name='タイトル')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.page')),
            ],
            options={
                'verbose_name': '企業情報 Translation',
                'db_table': 'core_page_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteConfigurationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('company_name', models.CharField(help_text='会社名を入力します。', max_length=200, verbose_name='会社名')),
                ('company_address', models.CharField(help_text='住所を入力します。', max_length=200, verbose_name='住所')),
                ('banner_slogan', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='バナーのスローガンを入力します。', null=True, verbose_name='バナーのスローガン')),
                ('banner_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='バナーの説明文を入力します。', null=True, verbose_name='バナーの説明文')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.siteconfiguration')),
            ],
            options={
                'verbose_name': 'サイト構成 Translation',
                'db_table': 'core_siteconfiguration_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
