# Generated by Django 6.0.3 on 2026-03-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='key',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url_prefix',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='prefix',
            field=models.CharField(blank=True, help_text='Prefix を入力します。 e.g., about, news, contact, etc.', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='メニュー項目を表示するかどうかを選択します。', verbose_name='表示する'),
        ),
    ]
