# Generated by Django 6.0.3 on 2026-03-26 09:24

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_menuitem_key_remove_menuitem_url_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='prefecture',
            field=models.CharField(blank=True, choices=[('hokkaido', '北海道'), ('aomori', '青森県'), ('iwate', '岩手県'), ('miyagi', '宮城県'), ('akita', '秋田県'), ('yamagata', '山形県'), ('fukushima', '福島県'), ('ibaraki', '茨城県'), ('tochigi', '栃木県'), ('gunma', '群馬県'), ('saitama', '埼玉県'), ('chiba', '千葉県'), ('tokyo', '東京都'), ('kanagawa', '神奈川県'), ('niigata', '新潟県'), ('toyama', '富山県'), ('ishikawa', '石川県'), ('fukui', '福井県'), ('yamanashi', '山梨県'), ('nagano', '長野県'), ('gifu', '岐阜県'), ('shizuoka', '静岡県'), ('aichi', '愛知県'), ('mie', '三重県'), ('shiga', '滋賀県'), ('kyoto', '京都府'), ('osaka', '大阪府'), ('hyogo', '兵庫県'), ('nara', '奈良県'), ('wakayama', '和歌山県'), ('tottori', '鳥取県'), ('shimane', '島根県'), ('okayama', '岡山県'), ('hiroshima', '広島県'), ('yamaguchi', '山口県'), ('tokushima', '徳島県'), ('kagawa', '香川県'), ('ehime', '愛媛県'), ('kochi', '高知県'), ('fukuoka', '福岡県'), ('saga', '佐賀県'), ('nagasaki', '長崎県'), ('kumamoto', '熊本県'), ('oita', '大分県'), ('miyazaki', '宮崎県'), ('kagoshima', '鹿児島県'), ('okinawa', '沖縄県')], max_length=50, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='globalnetworklocation',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='拠点の表示順序を指定します。', verbose_name='並び順'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='site_config',
            field=models.ForeignKey(default=core.models.SiteConfiguration.get_solo, help_text='メニュー項目を入力します。', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.siteconfiguration', verbose_name='サイト構成'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, help_text='ニュースを公開するかどうかを設定します。', verbose_name='公開済み'),
        ),
        migrations.AlterField(
            model_name='news',
            name='order',
            field=models.PositiveIntegerField(db_index=True, help_text='ニュースの表示順序を指定します。', verbose_name='並び順'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='URLに使用されるスラッグを入力します。', max_length=100, unique=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True, help_text='ページを公開するかどうかを設定します。', verbose_name='公開済み'),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(db_index=True, help_text='ページの表示順序を指定します。', verbose_name='並び順'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='URLに使用されるスラッグを入力します。', max_length=200, unique=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='ロゴ画像をアップロードします。', null=True, upload_to='logo/', verbose_name='ロゴイメージ'),
        ),
    ]
