# Generated by Django 6.0.3 on 2026-03-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_prefecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_email',
            field=models.EmailField(default='011@jobcre.net', help_text='お問い合わせがあった際に通知を送信するメールアドレスを入力します。', max_length=100, verbose_name='お問い合わせ通知用メールアドレス'),
        ),
    ]
