# Generated by Django 6.0.3 on 2026-03-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfiguration_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_email',
            field=models.CharField(default='011@jobcre.net', help_text='お問い合わせがあった際に通知を送信するメールアドレスを入力します。複数を指定する場合はカンマ(,)で区切ってください。', max_length=255, verbose_name='お問い合わせ通知用メールアドレス'),
        ),
    ]
