# Generated by Django 6.0.3 on 2026-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_siteconfiguration_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_confirm',
            field=models.EmailField(default='', max_length=254, verbose_name='メールアドレス(確認)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='greetingtranslation',
            name='ceo_name',
            field=models.CharField(default='CEO Name', help_text='代表取締役氏名を入力します。', max_length=100, verbose_name='代表取締役氏名'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_email',
            field=models.CharField(help_text='お問い合わせがあった際に通知を送信するメールアドレスを入力します。複数を指定する場合はカンマ(,)で区切ってください。', max_length=255, verbose_name='お問い合わせ通知用メールアドレス'),
        ),
    ]
